

CREATE TABLE hcm_content (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name  TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hcm_data (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content  TEXT NOT NULL,
  data  TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
